config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "pages#index"
  resources :questions do
    resources :answers, only: [ :create, :destroy, :edit, :update ]
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_question!, only: [ :create ]
  before_action :set_answer!, only: [ :destroy, :edit, :update ]
  def create
    @answer = @question.answers.build answer_params
    if @answer.save
      flash[:success] = "Answer created!"
      redirect_to question_path(@question)
    else
      @answers = @question.answers.order created_at: :desc
      render "questions/show"
    end
  end

  def destroy
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    flash[:success] = "Answer Deleted!"
    redirect_to question_path(@question)
  end

  def edit
    @answer = @question.answers.find(params[:id])
  end
  def update
    @answer = @question.answers.find(params[:id])
    if @answer.update(answer_params)
      flash[:success] = "Answer Updated!"
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render "questions/show"
    end
  end

  private
  def answer_params
    params.require(:answer).permit :body
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    set_question!
    @answer = @question.answers.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include ErrorHandling
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def not_found(exception)
      logger.warn exception.message
      render file: "public/404.html", status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @user = params["name"].blank? ? "User" : params["name"]
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: [ :show, :edit, :update, :destroy ]
  def index
    @questions = Question.all.order(:created_at).page params[:page]
  end
  def new
    @question = Question.new
  end

  def create
    @question = Question.new questions_params

    if @question.save
      flash[:success] = "Question created!"
      redirect_to questions_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @question.update questions_params
      flash[:success] = "Question updated!"
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = "Question deleted!"
    redirect_to questions_path
  end

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order created_at: :desc
  end

  private
  def set_question!
    @question = Question.find(params[:id])
  end

  def questions_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "QuestIt"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  def nav_link(link_text, link_path)
    class_name = @current_page == link_text  ? "nav-link active" : "nav-link"
    content_tag(:li, class: "nav-item") do
      link_to link_text, link_path, class: class_name
    end
  end
  def set_current_page(title)
    @current_page = title
  end
end

app/views/answers/_answers.erb
<%= tag.div class: "my-", id:  dom_id(answer) do %>
  <p><%= sanitize answer.body %></p>
  <%= link_to "Delete", question_answer_path(question, answer), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" }%>
  <%= link_to "Edit", edit_question_answer_path(question, answer), class: "btn btn-warning btn-sm"%>
<% end %>

app/views/answers/_form.erb
<%= render 'shared/errors', item: @answer %>

<%= form_with model: [@question, @answer], local: true do |f| %>

  <div class="mb-3">
    <%= f.label :body, class: "form-label" %>
    <%= f.text_area :body, class: "form-control", placeholder: "Answer" %>
  </div>

  <div>
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/answers/edit.erb
<%= render "answers/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :full_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <%= nav_link "Home", root_path%>
          <%= nav_link "Questions", questions_path%>
          <%= nav_link "Health", rails_health_check_path%>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<% provide :full_title, "Home"%>
<% set_current_page "Home"%>

<h1 class="display-4">Hello, <%= @user %>!</h1>
<p class="lead">Welcome to our website. We are glad to have you here.</p>
<hr class="my-4">
<p>Here are some features you might find interesting:</p>
<ul class="list-group mb-4">
  <li class="list-group-item">Feature 1: User-friendly interface</li>
  <li class="list-group-item">Feature 2: Responsive design</li>
  <li class="list-group-item">Feature 3: Customizable settings</li>
</ul>

app/views/questions/_form.erb
<%= render 'shared/errors', item: @question %>

<%= form_with model: @question, local: true do |f| %>
  <div class="mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="mb-3">
    <%= f.label :body, class: "form-label" %>
    <%= f.text_area :body, class: "form-control", placeholder: "Content" %>
  </div>

  <div>
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<% provide :full_title, "Edit question"%>
<% set_current_page "Questions"%>

<h1 class="mb-4">Edit question</h1>

<%= render "form" %>

app/views/questions/index.erb
<% provide :full_title, "Questions"%>
<% set_current_page "Questions"%>

<h1 class="mb-4">Questions</h1>
<%= link_to "<i class='bi bi-plus'></i> New Question".html_safe, new_question_path, class: "btn btn-primary mb-3" %>

<%= render 'shared/alert' %>

<% @questions.each do |question| %>
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= question.title %></h5>
      <p class="card-text"><%= truncate sanitize(question.body), length: 120 %></p>
      <div class="d-flex">
        <%= link_to "<i class='bi bi-eye'></i> View".html_safe, question_path(question), class: "btn btn-info btn-sm me-2" %>
        <%= link_to "<i class='bi bi-pencil'></i> Edit".html_safe, edit_question_path(question), class: "btn btn-warning btn-sm me-2" %>
        <%= link_to "<i class='bi bi-trash'></i> Delete".html_safe, question_path(question), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
      </div>
    </div>
  </div>
<% end %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<% provide :full_title, "New question"%>
<% set_current_page "Questions"%>

<h1 class="mb-4">New question</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<% provide :full_title, "Question Details"%>
<% set_current_page "Questions"%>

<h1 class="mb-4">Question Details</h1>

<%= render 'shared/alert' %>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title"><%= @question.title %></h5>
    <p class="card-text"><%= sanitize @question.body %></p>
    <div class="d-flex">
      <%= link_to "<i class='bi bi-pencil'></i> Edit".html_safe, edit_question_path(@question), class: "btn btn-warning me-2" %>
      <%= link_to "<i class='bi bi-trash'></i> Delete".html_safe, question_path(@question), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

<%= render "answers/form" %>
<hr>
<% if @answers.present? %>
  <%#= render @answers %>
  <%= render partial: "answers/answers", collection: @answers, as: :answer, locals: {question: @question }%>
  <hr>
<% else %>
  <p>There is no answers</p>
<% end %>
<%= link_to "<i class='bi bi-arrow-left'></i> Back to Questions".html_safe, questions_path, class: "btn btn-primary" %>

app/views/shared/_alert.erb
<% flash.each do |k, v| %>
  <%=tag.div v, class: "alert alert-#{k}", role: "alert" %>
<% end %>

app/views/shared/_errors.erb
<% if item.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">Oops! There were some errors:</h4>
    <ul class="mb-0">
      <% item.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>